CoreDepartman/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace CoreDepartman.Models
{
    public class Context:DbContext
    {   
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=DESKTOP-UQPST9J;database=corepersonel;integrated security=true; TrustServerCertificate=True;");
        }
        public DbSet<Departmanlar> Departmanlars { get; set; }

        public DbSet<Personel> Personels { get; set; } 
    }
}

CoreDepartman/Models/Departmanlar.cs
using System.ComponentModel.DataAnnotations;

namespace CoreDepartman.Models
{
    public class Departmanlar
    {
        [Key]
        public int id { get; set; }

        public string departmanad { get; set; }
        public List<Personel>Personels { get; set; }
    }
}

CoreDepartman/Models/ErrorViewModel.cs
namespace CoreDepartman.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreDepartman/Models/Personel.cs
using System.ComponentModel.DataAnnotations;

namespace CoreDepartman.Models
{
    public class Personel
    {
        [Key]
        public int perid { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }

        public Departmanlar Depart { get; set; }

    }
}

CoreDepartman/Controllers/DepartController.cs
using CoreDepartman.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreDepartman.Controllers
{
    public class DepartController : Controller
    {
        Context c = new Context();
        public IActionResult Index()
        {
           var values=c.Departmanlars.ToList();
            return View(values);
        }

        [HttpGet]
        public IActionResult YeniDepartman()
        {
            return View();
        }

        [HttpPost]
        public IActionResult YeniDepartman(Departmanlar d)
        {
            c.Departmanlars.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DepartmanSil( int id)
        {
            var values=c.Departmanlars.Find(id);
            c.Departmanlars.Remove(values);
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public IActionResult DepartmanGetir(int id)
        {
            var values = c.Departmanlars.Find(id);
            return View("DepartmanGetir",values);

        }
        public IActionResult DepartmanGuncelle(Departmanlar d)
        {
            var dep = c.Departmanlars.Find(d.id);
            dep.departmanad = d.departmanad;
            c.SaveChanges();
            return RedirectToAction("Index");

        }


    }
}

CoreDepartman/Controllers/HomeController.cs
using CoreDepartman.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CoreDepartman.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoreDepartman/Controllers/PersonelController.cs
using CoreDepartman.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreDepartman.Controllers
{
    public class PersonelController : Controller
    {
        Context c = new Context();
        public IActionResult Index()
        {
            var deger = c.Personels.ToList();

            return View(deger);
        }
    }
}

CoreDepartman/Views/Depart/DepartmanGetir.cshtml
@model CoreDepartman.Models.Departmanlar
@{
    ViewData["Title"] = "DepartmanGetir";
    Layout = "~/Views/Shared/_TestLayot.cshtml";
}
<br/>
@using (Html.BeginForm("DepartmanGuncelle","Depart", FormMethod.Post))
{
    <b>Departman ID</b>
    @Html.TextBoxFor(x=>x.id, new {@class="form-control"})
    <br/>
    <b>Departman Adı</b>
    @Html.TextBoxFor(x=>x.departmanad, new {@class="form-control"})
    <br/>
    <button class="btn btn-info" style="background-color:crimson">Departman Güncelle</button>
    
}

CoreDepartman/Views/Depart/Index.cshtml
@using CoreDepartman.Models
@model List<Departmanlar>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayot.cshtml";
}

<br/>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Departman</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach(var item in Model)
    {
    <tr>
        <td>@item.id</td>
        <td>@item.departmanad</td>
        <td><a href="/Depart/DepartmanSil/@item.id" class="btn btn-warning">Sil</a></td>
        <td><a href="/Depart/DepartmanGetir/@item.id " class="btn btn-secondary">Güncelle</a></td>
        <td><a href="#" class="btn btn-info">Detaylar</a></td>
    </tr>
    }
</table>
<a href="/Depart/YeniDepartman/" class="btn btn-primary">Yeni Departman</a>

CoreDepartman/Views/Depart/YeniDepartman.cshtml
@model CoreDepartman.Models.Departmanlar
@{
    ViewData["Title"] = "YeniDepartman";
    Layout = "~/Views/Shared/_TestLayot.cshtml";
}

<form class="form-group" method="post">

    <b>Departman Adı</b>
    @Html.TextBoxFor(x=>x.departmanad, new {@class="form-control"})
    </br>
    <button class="btn btn-info">Departman Ekle</button>
</form>

CoreDepartman/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreDepartman/Views/Personel/Index.cshtml
@using CoreDepartman.Models
@model List<Personel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayot.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>ŞEHİR</th>
        <th>DEPARTMAN</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.perid</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.Sehir</td>
            <td>@item.Depart.departmanad</td>
            <td><a href="/Depart/DepartmanSil/@item.perid" class="btn btn-warning">Sil</a></td>
            <td><a href="/Depart/DepartmanGetir/@item.perid " class="btn btn-secondary">Güncelle</a></td>
            <td><a href="#" class="btn btn-info">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Depart/YeniDepartman/" class="btn btn-primary">Yeni Personel</a>

CoreDepartman/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreDepartman</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreDepartman.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreDepartman</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CoreDepartman - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoreDepartman/Views/Shared/_TestLayot.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="/Depart/Index/" class="w3-bar-item w3-button">Departmanlar</a>
        <a href="/Personel/Index/" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>ASP.NET CORE MVC 5 GELİŞTİRME</h1>
        </div>

        

        <div class="w3-container">
           @RenderBody();
        </div>

    </div>

</body>
</html>